all:
	#gcc -o shubert shubert.c -lm
	#gcc -o shared_double shared_double.c -lrt
	gcc -o problem1_client problem1_client.c -lrt
	gcc -o problem1_server problem1_server.c -lrt
	gcc -o server_2 server_2.c
	gcc -o client_2 client_2.c
	gcc -o 3a 3a.c -lm -lrt
	gcc -o 3b 3b.c -lm -lrt
	gcc -o 3c_server 3c_server.c -lm -lrt
	gcc -o 3c_client 3c_client.c -lm -lrt
