all:
	gcc -o prob1_server prob1_server.c -lrt -lpthread
	gcc -o prob1_client prob1_client.c -lrt -lpthread
	gcc -o prob2_server prob2_server.c -lrt -lpthread
	gcc -o prob2_client prob2_client.c -lrt -lpthread
	gcc -o prob3 prob3.c -lpthread -lrt
	gcc -o server_2 server_2.c
	gcc -o client_2 client_2.c
